--1
SELECT NAZWISKO, ETAT, Z.ID_ZESP, NAZWA FROM PRACOWNICY P JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP ORDER BY NAZWISKO;

--2
SELECT NAZWISKO, ETAT, Z.ID_ZESP, NAZWA FROM PRACOWNICY P JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP WHERE Z.ADRES = 'PIOTROWO 3A' ORDER BY NAZWISKO;

--3
SELECT NAZWISKO, ETAT, PLACA_POD, E.PLACA_MIN, E.PLACA_MAX FROM PRACOWNICY P JOIN ETATY E ON P.ETAT = E.NAZWA ORDER BY NAZWA, NAZWISKO;

--4
SELECT NAZWISKO, ETAT, PLACA_POD, E.PLACA_MIN, E.PLACA_MAX,
CASE
    WHEN PLACA_POD BETWEEN PLACA_MAX AND PLACA_MIN THEN 'OK'
    ELSE 'NIE'
END AS CZY_PENSJA_OK
FROM PRACOWNICY P JOIN ETATY E ON P.ETAT = E.NAZWA ORDER BY NAZWA, NAZWISKO;

--5
SELECT * FROM (SELECT NAZWISKO, ETAT, PLACA_POD, E.PLACA_MIN, E.PLACA_MAX,
CASE
    WHEN PLACA_POD BETWEEN PLACA_MAX AND PLACA_MIN THEN 'OK'
    ELSE 'NIE'
END AS CZY_PENSJA_OK
FROM PRACOWNICY P JOIN ETATY E ON P.ETAT = E.NAZWA ORDER BY NAZWA, NAZWISKO ) WHERE CZY_PENSJA_OK='NIE'

--6
SELECT NAZWISKO, PLACA_POD, ETAT, NAZWA AS KAT_PLAC, PLACA_MIN, PLACA_MAX FROM PRACOWNICY INNER JOIN ETATY ON PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX ORDER BY NAZWISKO;

--7
SELECT NAZWISKO, PLACA_POD, ETAT, NAZWA AS KAT_PLAC, PLACA_MIN, PLACA_MAX
FROM PRACOWNICY INNER JOIN ETATY ON
PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX WHERE NAZWA='SEKRETARKA' ORDER BY NAZWISKO;

--8
SELECT P1.NAZWISKO AS PRACOWNIK, P1.ID_PRAC, P2.NAZWISKO AS SZEF, P1.ID_SZEFA FROM PRACOWNICY P1 JOIN PRACOWNICY P2 ON P1.ID_SZEFA = P2.ID_PRAC ORDER BY P1.NAZWISKO;

--9
SELECT P1.NAZWISKO AS PRACOWNIK, TO_CHAR(P1.ZATRUDNIONY,'YYYY.MM.DD') AS PRAC_ZATRUDNIONY, P2.NAZWISKO AS SZEF, TO_CHAR(P2.ZATRUDNIONY,'YYYY.MM.DD') AS SZEF_ZATRUDNIONY, FLOOR((P1.ZATRUDNIONY-P2.ZATRUDNIONY)/365) AS LATA
FROM PRACOWNICY P1 JOIN PRACOWNICY P2 ON P1.ID_SZEFA = P2.ID_PRAC WHERE FLOOR((P1.ZATRUDNIONY-P2.ZATRUDNIONY)/365) <= 10 ORDER BY PRAC_ZATRUDNIONY, P1.NAZWISKO;

--10
SELECT NAZWA, COUNT(NAZWA) AS LICZBA, SUM(PLACA_POD)/COUNT(NAZWA) AS SREDNIA_PLACA FROM PRACOWNICY P JOIN ZESPOLY Z USING(ID_ZESP) GROUP BY NAZWA ORDER BY NAZWA;

--11
SELECT NAZWA,
CASE
    WHEN COUNT(NAZWA) <= 2  THEN 'MAŁY'
    WHEN COUNT(NAZWA) >= 7 THEN 'DUŻY'
    ELSE 'ŚREDNI'
END AS ETYKIETA
FROM PRACOWNICY P JOIN ZESPOLY Z USING(ID_ZESP) GROUP BY NAZWA HAVING COUNT(NAZWA) > 0 ORDER BY NAZWA
