--1
CREATE TABLE PROJEKTY(
    ID_PROJEKTU NUMBER(4) GENERATED ALWAYS AS IDENTITY,
     OPIS_PROJEKTU VARCHAR(20),
     DATA_ROZPOCZECIA DATE DEFAULT CURRENT_DATE,
     DATA_ZAKONCZENIA DATE,
     FUNDUSZ NUMBER(7,2));

--2
INSERT INTO PROJEKTY(OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
    VALUES('Indeksy bitmapowe', '1999-04-02', '2001-08-31', 25000);
INSERT INTO PROJEKTY(OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
    VALUES('Sieci kręgosłupowe', DEFAULT, NULL, 19000);

--3
SELECT ID_PROJEKTU, OPIS_PROJEKTU FROM PROJEKTY;

--4
INSERT INTO PROJEKTY (ID_PROJEKTU, OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
    VALUES (10, 'Indeksy drzewiaste', '2013-12-24', '2014-01-01', 1200);

-- POLECENIE ZAKONCZYLO SIE NIEPOWODZENIEM, POPRAWNA WERSJA:
INSERT INTO PROJEKTY (OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
    VALUES ('Indeksy drzewiaste', '2013-12-24', '2014-01-01', 1200);

--5
UPDATE PROJEKTY SET ID_PROJEKTU=10 WHERE OPIS_PROJEKTU='Indeksy bitmapowe';
-- POLECENIE ZAKONCZYLO SIE NIEPOWODZENIEM

--6
CREATE TABLE PROJEKTY_KOPIA AS SELECT * FROM PROJEKTY;
SELECT * FROM PROJEKTY_KOPIA;

--7
INSERT INTO PROJEKTY_KOPIA (ID_PROJEKTU, OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
    VALUES (10, 'Sieci lokalne', CURRENT_DATE, CURRENT_DATE + INTERVAL '1' YEAR, 24500);

-- POLECENIE ZAKONCZYLO SIE POWODZENIEM PONIEWAZ ATRYBUT ID_PROJEKTU NIE ODZIEDZICZYL WLASCIWOSCI 'GENERATED ALWAYS AS IDENTITY'

--8
DELETE FROM PROJEKTY WHERE OPIS_PROJEKTU='Indeksy drzewiaste';
-- REKORD TEN NIE ZOSTAL AUTOMATYCZNIE USUNIETY Z RELACJI PROJEKTY_KOPIA

--9
SELECT TABLE_NAME FROM TABS;

