--1
SELECT NAZWISKO, ETAT, ID_ZESP FROM PRACOWNICY WHERE ID_ZESP = (SELECT ID_ZESP FROM PRACOWNICY WHERE NAZWISKO='BRZEZINSKI') ORDER BY NAZWISKO;

--2
SELECT NAZWISKO, ETAT, NAZWA FROM PRACOWNICY JOIN ZESPOLY USING(ID_ZESP) WHERE ID_ZESP = (SELECT ID_ZESP FROM PRACOWNICY WHERE NAZWISKO='BRZEZINSKI') ORDER BY NAZWISKO;

--3
SELECT NAZWISKO, ETAT, TO_CHAR(ZATRUDNIONY,'YYYY/MM/DD') AS ZATRUDNIONY FROM PRACOWNICY WHERE ZATRUDNIONY = (SELECT MIN(ZATRUDNIONY) FROM PRACOWNICY WHERE ETAT='PROFESOR');

--4
SELECT NAZWISKO, TO_CHAR(ZATRUDNIONY, 'YYYY/MM/DD') AS ZATRUDNIONY, ID_ZESP FROM PRACOWNICY WHERE (ZATRUDNIONY,ID_ZESP) IN (SELECT MAX(ZATRUDNIONY), ID_ZESP FROM PRACOWNICY GROUP BY ID_ZESP) ORDER BY ZATRUDNIONY;

--5
SELECT ID_ZESP, NAZWA, ADRES FROM ZESPOLY WHERE ID_ZESP = (SELECT ID_ZESP FROM ZESPOLY LEFT JOIN PRACOWNICY USING(ID_ZESP) GROUP BY ID_ZESP HAVING COUNT(ID_PRAC) = 0);

--6
SELECT NAZWISKO FROM PRACOWNICY WHERE ETAT='PROFESOR' AND NAZWISKO NOT IN (SELECT P1.NAZWISKO FROM PRACOWNICY P1 JOIN PRACOWNICY P2 ON P2.ID_SZEFA = P1.ID_PRAC WHERE P1.ETAT='PROFESOR' AND P2.ETAT='STAZYSTA');

--7
SELECT NAZWA, SUMA_PLAC FROM (SELECT Z.NAZWA, SUM(P.PLACA_POD) AS SUMA_PLAC FROM PRACOWNICY P JOIN ZESPOLY Z USING(ID_ZESP) GROUP BY Z.NAZWA ORDER BY SUMA_PLAC DESC) WHERE ROWNUM = 1;

--8
SELECT ID_ZESP, SUMA_PLAC FROM (SELECT ID_ZESP, SUM(P.PLACA_POD) AS SUMA_PLAC FROM PRACOWNICY P JOIN ZESPOLY Z USING(ID_ZESP) GROUP BY ID_ZESP ORDER BY SUMA_PLAC DESC) WHERE ROWNUM = 1;

--9
SELECT Z.NAZWA, COUNT(ID_PRAC) AS ILU_PRACOWNIKOW FROM ZESPOLY Z JOIN PRACOWNICY P USING(ID_ZESP) GROUP BY Z.NAZWA HAVING COUNT(ID_PRAC) > (SELECT COUNT(ID_PRAC) AS ILU_PRACOWNIKOW FROM ZESPOLY Z JOIN PRACOWNICY P USING(ID_ZESP) WHERE Z.NAZWA = 'ADMINISTRACJA' GROUP BY Z.NAZWA) ORDER BY Z.NAZWA;

--10
SELECT ETAT FROM PRACOWNICY GROUP BY(ETAT) HAVING COUNT(ETAT) = (SELECT MAX(L) FROM (SELECT COUNT(ETAT) AS L, ETAT FROM PRACOWNICY GROUP BY ETAT));

--11
SELECT ETAT, LISTAGG(NAZWISKO, ',') WITHIN GROUP (ORDER BY NAZWISKO) AS "PRACOWNICY" FROM PRACOWNICY WHERE ETAT IN (SELECT ETAT FROM PRACOWNICY GROUP BY(ETAT) HAVING COUNT(ETAT) = (SELECT MAX(L) FROM (SELECT COUNT(ETAT) AS L, ETAT FROM PRACOWNICY GROUP BY ETAT))) GROUP BY ETAT;

--12 NIE DZIALA
SELECT DISTINCT P1.ID_PRAC FROM PRACOWNICY P1 JOIN PRACOWNICY P2 ON P2.ID_SZEFA = P1.ID_PRAC
SELECT ID_PRAC, ID_SZEFA FROM PRACOWNICY WHERE ID_SZEFA IS NOT NULL
SELECT P1.PLACA_POD AS PLACA_PRACOWNIKA, P2.PLACA_POD AS PLACA_SZEFA FROM PRACOWNICY P1 JOIN (SELECT ID_PRAC, ID_SZEFA FROM PRACOWNICY WHERE ID_SZEFA IS NOT NULL) P2 ON P1.ID_SZEFA = P2.ID_PRAC
