--1
SELECT ID_ZESP, NAZWA, ADRES FROM ZESPOLY Z WHERE NOT EXISTS (SELECT * FROM PRACOWNICY WHERE ID_ZESP = Z.ID_ZESP);

--2
SELECT NAZWISKO, PLACA_POD, ETAT FROM PRACOWNICY P WHERE PLACA_POD > (SELECT AVG(PLACA_POD) FROM PRACOWNICY WHERE ETAT = P.ETAT) ORDER BY PLACA_POD DESC;

--3
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY P WHERE PLACA_POD >= (SELECT 0.75*PLACA_POD FROM PRACOWNICY WHERE ID_PRAC = P.ID_SZEFA) ORDER BY NAZWISKO;

--4
SELECT NAZWISKO FROM PRACOWNICY P WHERE P.ETAT = 'PROFESOR' AND NOT EXISTS (SELECT NAZWISKO FROM PRACOWNICY WHERE ETAT='STAZYSTA' AND P.ID_PRAC = ID_SZEFA);

--5
SELECT Z.NAZWA, P1.MAKS AS MAKS_SUMA_PLAC FROM
    (SELECT MAX(SUM(PLACA_POD)) AS MAKS FROM PRACOWNICY GROUP BY ID_ZESP) P1
    JOIN
    (SELECT SUM(PLACA_POD) AS MAKS, ID_ZESP FROM PRACOWNICY GROUP BY ID_ZESP) P2
    ON P1.MAKS = P2.MAKS
    JOIN ZESPOLY Z ON Z.ID_ZESP=P2.ID_ZESP;

--6
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY P WHERE (SELECT COUNT(*) FROM PRACOWNICY WHERE P.PLACA_POD < PLACA_POD) < 3 ORDER BY PLACA_POD DESC;

--7
SELECT TO_CHAR(ZATRUDNIONY,'YYYY') AS ROK, COUNT(*) AS LICZBA FROM PRACOWNICY GROUP BY TO_CHAR(ZATRUDNIONY,'YYYY') ORDER BY LICZBA DESC;

--8
SELECT TO_CHAR(ZATRUDNIONY,'YYYY') AS ROK, COUNT(*) AS LICZBA FROM PRACOWNICY
GROUP BY TO_CHAR(ZATRUDNIONY,'YYYY')
HAVING COUNT(*) = (SELECT(MAX(COUNT(*))) FROM PRACOWNICY GROUP BY TO_CHAR(ZATRUDNIONY,'YYYY'));

--9
SELECT NAZWISKO, PLACA_POD, PLACA_POD - (SELECT AVG(PLACA_POD) FROM PRACOWNICY WHERE ID_ZESP = P.ID_ZESP) AS RÓŻNICA FROM PRACOWNICY P ORDER BY NAZWISKO; --wykorzystanie podzapytania w klauzuli select
SELECT NAZWISKO, PLACA_POD, PLACA_POD - ŚREDNIA AS RÓŻNICA FROM (SELECT ID_ZESP, AVG(PLACA_POD) AS ŚREDNIA FROM PRACOWNICY GROUP BY ID_ZESP) JOIN PRACOWNICY USING(ID_ZESP) ORDER BY NAZWISKO; -- wykorzystanie podzapytania w klauzuli from

--10
SELECT NAZWISKO, PLACA_POD, PLACA_POD - (SELECT AVG(PLACA_POD) FROM PRACOWNICY WHERE ID_ZESP = P.ID_ZESP) AS RÓŻNICA FROM PRACOWNICY P WHERE PLACA_POD - (SELECT AVG(PLACA_POD) FROM PRACOWNICY WHERE ID_ZESP = P.ID_ZESP) > 0 ORDER BY NAZWISKO;
SELECT NAZWISKO, PLACA_POD, PLACA_POD - ŚREDNIA AS RÓŻNICA FROM (SELECT ID_ZESP, AVG(PLACA_POD) AS ŚREDNIA FROM PRACOWNICY GROUP BY ID_ZESP) JOIN PRACOWNICY USING(ID_ZESP) WHERE PLACA_POD - ŚREDNIA > 0 ORDER BY NAZWISKO;

--11
SELECT NAZWISKO, (SELECT COUNT(*) FROM PRACOWNICY WHERE P.ID_PRAC = ID_SZEFA) AS PODWŁADNI FROM PRACOWNICY P JOIN ZESPOLY Z USING(ID_ZESP) WHERE ETAT='PROFESOR' AND ADRES LIKE '%PIOTROWO%' ORDER BY PODWŁADNI DESC;

--12
SELECT DISTINCT NAZWA, ROUND((SELECT AVG(PLACA_POD) FROM PRACOWNICY WHERE ID_ZESP = Z.ID_ZESP),2)
AS ŚREDNIA_W_ZESPOLE,
ROUND((SELECT AVG(PLACA_POD) FROM PRACOWNICY),2) AS ŚREDNIA_OGÓLNA,
CASE
    WHEN ROUND((SELECT AVG(PLACA_POD) FROM PRACOWNICY WHERE ID_ZESP = Z.ID_ZESP),2) >= ROUND((SELECT AVG(PLACA_POD) FROM PRACOWNICY),2) THEN ':)'
    WHEN ROUND((SELECT AVG(PLACA_POD) FROM PRACOWNICY WHERE ID_ZESP = Z.ID_ZESP),2) < ROUND((SELECT AVG(PLACA_POD) FROM PRACOWNICY),2) THEN ':('
    ELSE '???'
END AS NASTROJE
FROM ZESPOLY Z LEFT JOIN PRACOWNICY P ON Z.ID_ZESP = P.ID_ZESP ORDER BY NAZWA;

--13
SELECT DISTINCT NAZWA, PLACA_MIN, PLACA_MAX FROM PRACOWNICY P LEFT JOIN ETATY E ON ETAT=NAZWA ORDER BY (SELECT COUNT(*) FROM PRACOWNICY WHERE ETAT=E.NAZWA) DESC, NAZWA;
