--1
INSERT INTO PRACOWNICY(ID_PRAC, NAZWISKO, ETAT, ZATRUDNIONY, PLACA_POD, ID_ZESP)
    VALUES(250, 'KOWALSKI', 'ASYSTENT', '2015-01-13', 1500, 10);

INSERT INTO PRACOWNICY(ID_PRAC, NAZWISKO, ETAT, ZATRUDNIONY, PLACA_POD, ID_ZESP)
    VALUES(260, 'ADAMSKI', 'ASYSTENT', '2014-09-10', 1500, 10);

INSERT INTO PRACOWNICY(ID_PRAC, NAZWISKO, ETAT, ZATRUDNIONY, PLACA_POD, PLACA_DOD, ID_ZESP)
    VALUES(270, 'NOWAK', 'ADIUNKT', '1990-05-01', 2050, 540, 20);

SELECT * FROM PRACOWNICY WHERE ID_PRAC >= 250;

--2
UPDATE PRACOWNICY P
SET (PLACA_POD, PLACA_DOD) = (
    SELECT 1.1*PLACA_POD, NVL(PLACA_DOD*1.2, 100) FROM PRACOWNICY WHERE ID_PRAC = P.ID_PRAC
)
WHERE ID_PRAC >= 250;

SELECT * FROM PRACOWNICY WHERE ID_PRAC >= 250;

--3
INSERT INTO ZESPOLY(ID_ZESP, NAZWA, ADRES) VALUES(60, 'BAZY DANYCH', 'PIOTROWO 2');
SELECT * FROM ZESPOLY WHERE ID_ZESP = 60;

--4
UPDATE PRACOWNICY P SET ID_ZESP = (
    SELECT ID_ZESP FROM ZESPOLY WHERE NAZWA = 'BAZY DANYCH'
)
WHERE ID_PRAC >= 250;
SELECT * FROM PRACOWNICY WHERE ID_ZESP = 60;

--5
UPDATE PRACOWNICY P
SET P.ID_SZEFA = (SELECT ID_PRAC FROM PRACOWNICY WHERE NAZWISKO='MORZY')
WHERE P.ID_ZESP = 60;

SELECT * FROM PRACOWNICY WHERE ID_SZEFA = (SELECT ID_PRAC FROM PRACOWNICY WHERE NAZWISKO = 'MORZY')

--6
DELETE FROM ZESPOLY WHERE NAZWA='BAZY DANYCH';
-- POLECENIE ZAKONCZYLO SIE NIEPOWODZENIEM - ZE WZGLEDU NA OBECNOSC KLUCZA OBCEGO POWIAZANEGO Z ATRYBUTEM ID_ZESP W RELACJI PRACOWNICY

--7
--DELETE FROM PRACOWNICY WHERE ID_ZESP = (SELECT ID_ZESP FROM ZESPOLY WHERE NAZWA='BAZY DANYCH')
DELETE FROM PRACOWNICY WHERE ID_ZESP = 60;
DELETE FROM ZESPOLY WHERE NAZWA='BAZY DANYCH';

-- JAKO ZE W TABELI PRACOWNICY NIE BYLO REKORDOW POWIAZANYCH Z ZESPOLEM BAZ DANYCH - POLECENIE USUWANIA ZESPOLU ZAKONCZYLO SIE POMYSLNIE

--8
SELECT NAZWISKO, PLACA_POD, (SELECT 0.1*AVG(PLACA_POD) FROM PRACOWNICY WHERE ID_ZESP=P.ID_ZESP) AS PODWYZKA
FROM PRACOWNICY P ORDER BY NAZWISKO;

--9
UPDATE PRACOWNICY P SET P.PLACA_POD = P.PLACA_POD +
(SELECT 0.1*AVG(PLACA_POD) FROM PRACOWNICY WHERE ID_ZESP=P.ID_ZESP);
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY ORDER BY NAZWISKO;

--10
SELECT * FROM PRACOWNICY WHERE PLACA_POD = (SELECT MIN(PLACA_POD) FROM PRACOWNICY);

--11

UPDATE PRACOWNICY SET PLACA_POD = (
    SELECT ROUND(AVG(PLACA_POD),2) FROM PRACOWNICY
)
WHERE ID_PRAC = (SELECT ID_PRAC FROM PRACOWNICY WHERE PLACA_POD =(SELECT MIN(PLACA_POD) FROM PRACOWNICY));

SELECT * FROM PRACOWNICY WHERE ID_PRAC = 200;

--12
UPDATE PRACOWNICY SET PLACA_DOD = (
SELECT AVG(PLACA_POD) FROM PRACOWNICY WHERE ID_SZEFA = (SELECT ID_PRAC FROM PRACOWNICY WHERE NAZWISKO = 'MORZY'))
WHERE ID_ZESP = 20;

SELECT NAZWISKO, PLACA_DOD FROM PRACOWNICY WHERE ID_ZESP = 20;

--13
UPDATE PRACOWNICY SET PLACA_POD = PLACA_POD*1.25
WHERE ID_PRAC IN (SELECT ID_PRAC FROM PRACOWNICY P JOIN ZESPOLY Z USING(ID_ZESP) WHERE Z.NAZWA = 'SYSTEMY ROZPROSZONE');

SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY P JOIN ZESPOLY Z USING(ID_ZESP) WHERE Z.NAZWA = 'SYSTEMY ROZPROSZONE';

--14
DELETE FROM (SELECT P1.NAZWISKO FROM PRACOWNICY P1 JOIN PRACOWNICY
P2 ON P1.ID_SZEFA=P2.ID_PRAC WHERE P2.NAZWISKO='MORZY');

SELECT P1.NAZWISKO FROM PRACOWNICY P1 JOIN PRACOWNICY
P2 ON P1.ID_SZEFA=P2.ID_PRAC WHERE P2.NAZWISKO='MORZY';

--15
SELECT * FROM PRACOWNICY;

--16
CREATE SEQUENCE PRAC_SEQ START WITH 300 INCREMENT BY 10;

--17
INSERT INTO PRACOWNICY (ID_PRAC, NAZWISKO, ETAT, PLACA_POD)
    VALUES(PRAC_SEQ.NEXTVAL, 'Trąbczyński', 'STAZYSTA', 1000);
SELECT * FROM PRACOWNICY WHERE ID_PRAC = 300;

--18
UPDATE PRACOWNICY SET PLACA_DOD = (PRAC_SEQ.CURRVAL) WHERE ID_PRAC = 300;
SELECT * FROM PRACOWNICY WHERE ID_PRAC = 300;

--19
DELETE FROM PRACOWNICY WHERE NAZWISKO = 'Trąbczyński';

--20
CREATE SEQUENCE MALA_SEQ START WITH 2 INCREMENT BY 2 MAXVALUE 10;
SELECT MALA_SEQ.NEXTVAL FROM DUAL;
-- ZAPYTANIE ZAKONCZONE NIEPOWODZENIEM, POJAWIA SIE BLAD - W TYM MIEJSCU NUMER SEKWENCJI JEST NIEDOZWOLONY

--21
DROP SEQUENCE MALA_SEQ;
